# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  name: Default  # name of the pool to run this job in

steps:
- script:
    'mkdir -p ./TestHarness'
  displayName: 'Create TestHarness'

- script:
    'cd TestHarness'
  displayName: 'Set cwd to TestHarness'

- script:
    'git clone https://github.com/Keristero/CItestingSoftware'
  displayName: 'Clone Software repository'

- job: Test Harness
  steps:
    - template: test-harness-steps.yml
