# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  name: default  # name of the pool to run this job in

- script: |
    mkdir -p ./TestHarness
    cd TestHarness
  displayName: 'Create and set cwd to TestHarness'

- script: |
  git clone https://github.com/Keristero/CItestingSoftware
  cd TestHarness
displayName: 'Create and set cwd to TestHarness'

# Publish Test Results
# Publish Test Results to Azure Pipelines/TFS
- task: PublishTestResults@2
  condition: always()
  inputs:
    testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit
    testResultsFiles: '**/test-results*.xml' 
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    #mergeTestResults: false # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    #publishRunAttachments: true # Optional
